### ISSUE TITLE
Slow inference with CAD

### ISSUE THREAD

**Issue by acDante** [wangtz19/DecodingStrategy#1]
Thanks for the great work! I am trying your CAD implementation in my experiments but found the inference process was very slow. I used your example codes during inference. Do you have any ideas about what might be wrong?

**Comment by wangtz19** [comment]
I can run inference with CAD on my machine with an A100 GPU, maybe you can check whether the GPU is used ? By the way, what's your batch size?

**Comment by acDante** [comment]
It might be a problem with loading a model using `device_map="auto"` on multiple GPUs. The code becomes much faster if I run it on a single GPU.

**Comment by wangtz19** [comment]
Sure, you're right. We also found that running speed would severely slow down when loading on multiple GPUs during training or inference, and we chose to explicitly specify only one visible GPU through environment variables, like `CUDA_VISIBLE_DEVICES=0 python ....`
